server:
  port: 7070
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Banking
    username: root
    password:

  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update

  security:
    user:
      name: shrijana
      password: shrijana
